### ISSUE TITLE
Features + installation process

### ISSUE THREAD

**Issue by Thovi98** [NicoNex/TortugaSync#1]
Hello, I've come across this repo thanks to the main subject of the repo: "custom secure cloud system for Kobo eBooks"

This interest me greatly: I'm looking of a way to sync my annotations and highlights from my Kobo (currently I have Kobo sync with Calibre-Web, which is already great but lacks those features).
So a self-hosted implementation which acts like the official server would be so great!

Is this possible/planned with TortugaSync? Or what's the purpose of it?
And what are the steps for installing TortugaSync?
And how to connect the Kobo to it?

Thanks!

**Comment by NicoNex** [comment]
Hi, yup that's actually what i use it for. It can sync both the ebooks and the notes using SSH.
The only requirement is that you need to install nickel menu to use it, i have a fork of it in my repos that allows to have a process that runs longer than the maximum 10s (it can run for max 1 minute in my fork).

In the repo in the `cmd` folder you can find `tortuga` which is the "client" program that you should install on your kobo (by install i just mean compile it with `GOOS=linux` and `GOARCH=arm` and just place it in your kobo memory), then `vessellotron` which is a telegram bot for uploading the ebooks to the server (you can do this in a different way if you want) and `kraken` which is the webserver used to see the bookmarks that the kobo uploads to the server.

If you give an epub to vessellotron it will convert it to kepub automatically before storing it on the server, the other formats are fine.

In the repo I also provide the nikel menu config file.

I'm glad you like the project that I made for myself, if you need additional info don't hesitate to write here.

**Comment by NicoNex** [comment]
For what concerns the installation of tortuga:
navigate to `cmd/tortuga` and run the following commands to build it:
`go run hostkey.go <your hostname>`
`GOOS=linux GOARCH=arm go build`

The tortuga command when run normally downloads the missing ebooks from your server checking comparing their hashes to those created by vessellotron.
When run with the `-b` flag it will upload the bookmarks to a specific directory on the server.

Once the build is completed create a folder named `bin` in the Kobo folder and put the binary there.
Then you can put the nikel menu config file i provided in its specific path.

After the previous steps all you need to do is to create a telegram API token and run vessellotron in your server.
Same thing for kraken.

**Comment by Thovi98** [comment]
Thank you for those exhaustive answers!
I’ll make a try when I find some times :D
